name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # region Preparation
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Extract version from tag without the v
        id: get-version
        run: echo "v=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"

      # https://stackoverflow.com/questions/61919141/read-json-file-in-github-actions
      - name: Get Module JSON
        id: set_var
        run: |
          echo "PACKAGE_JSON=$(jq -c . < module.json)" >> $GITHUB_OUTPUT

      - name: Get Module ID
        id: module_id
        run: echo "module_id=${{fromJson(steps.set_var.outputs.PACKAGE_JSON).id}}" >> "$GITHUB_OUTPUT"

      - name: Get Module Title
        id: title
        run: echo "title=${{fromJson(steps.set_var.outputs.PACKAGE_JSON).title}}" >> "$GITHUB_OUTPUT"

      - name: Install packages
        run: npm ci
      # endregion

      # region Actual Work Steps
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: module.json
        env:
          version: ${{ steps.get-version.outputs.v }}
          manifest: https://github.com/${{ github.repository }}/releases/latest/download/module.json
          download: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.zip

      - name: Substitute manifest for prerelease
        if: github.event.release.prerelease
        id: sub_prerelease_manifest_version
        uses: devops-actions/variable-substitution@v1.2
        with:
          files: module.json
        env:
          manifest: https://raw.githubusercontent.com/${{ github.repository }}/next/module.json

      - name: Build distribution
        run: npm run build

      # Create a zip file with all files required by the module to add to the release.
      - name: Bundle into ZIP file
        run: zip -r9 ./module.zip module.json assets/ lang/ dist/ packs/ CHANGELOG.md LICENSE README.md

      # Create a release for this specific version.
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # Set this to false if you want to prevent updating existing releases.
          name: ${{ github.event.release.name }}
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
          artifacts: "./module.json, ./module.zip"
          omitDraftDuringUpdate: true
          omitPrereleaseDuringUpdate: true

      - name: Send Discord Ping
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: ${{ env.DISCORD_WEBHOOK != '' && !github.event.release.prerelease }}
        with:
          args: "${{ (steps.get-version.outputs.version-without-v == '1.0.0' && '<@&1127986401590382712>') || '' }} ${{steps.title.outputs.title}} has been updated to version `${{github.event.release.tag_name}}`!"
      # endregion
